services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    extra_hosts:
      - "cluster0-shard-00-00.7mbnl.mongodb.net:159.143.173.101"
      - "cluster0-shard-00-01.7mbnl.mongodb.net:159.143.173.140"
      - "cluster0-shard-00-02.7mbnl.mongodb.net:159.143.173.124"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
