import { connectDB } from "@/lib/mongodb";
import Endpoint from "@/lib/models/endpoint";
import { error } from "@/lib/helpers/api-response";
import { requireAuth } from "@/lib/helpers/auth-guard";

export async function GET() {
  try {
    await requireAuth();
    await connectDB();

    const endpoints = await Endpoint.find().sort({ createdAt: -1 });

    const total = endpoints.length;
    const up = endpoints.filter((e) => e.lastStatus === "UP").length;
    const down = endpoints.filter((e) => e.lastStatus === "DOWN").length;
    const degraded = endpoints.filter((e) => e.lastStatus === "DEGRADED").length;
    const avgUptime =
      total > 0
        ? (endpoints.reduce((sum, e) => sum + e.uptimePercentage, 0) / total).toFixed(2)
        : "100.00";

    const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Pulse Dashboard Summary</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px 20px; color: #1a1a1a; }
  h1 { font-size: 24px; border-bottom: 2px solid #6366f1; padding-bottom: 8px; }
  .stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin: 20px 0; }
  .stat { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; text-align: center; }
  .stat-value { font-size: 28px; font-weight: 700; }
  .stat-label { font-size: 12px; color: #6b7280; }
  .up { color: #22c55e; } .down { color: #ef4444; } .degraded { color: #eab308; }
  table { width: 100%; border-collapse: collapse; margin-top: 16px; font-size: 13px; }
  th { background: #f3f4f6; text-align: left; padding: 8px 12px; border: 1px solid #e5e7eb; }
  td { padding: 8px 12px; border: 1px solid #e5e7eb; }
  .meta { color: #6b7280; font-size: 13px; }
  @media print { body { padding: 0; } }
</style></head><body>
<h1>Pulse Dashboard Summary</h1>
<p class="meta">Generated: ${new Date().toISOString()}</p>
<div class="stats">
  <div class="stat"><div class="stat-value">${total}</div><div class="stat-label">Total Endpoints</div></div>
  <div class="stat"><div class="stat-value up">${up}</div><div class="stat-label">UP</div></div>
  <div class="stat"><div class="stat-value down">${down}</div><div class="stat-label">DOWN</div></div>
  <div class="stat"><div class="stat-value">${avgUptime}%</div><div class="stat-label">Avg Uptime</div></div>
</div>
<table>
<thead><tr><th>Name</th><th>URL</th><th>Status</th><th>Uptime</th><th>Response (ms)</th><th>Last Check</th></tr></thead>
<tbody>
${endpoints
  .map(
    (e) =>
      `<tr><td>${e.name}</td><td>${e.url}</td><td class="${(e.lastStatus || "").toLowerCase()}">${e.lastStatus || "PENDING"}</td><td>${e.uptimePercentage.toFixed(2)}%</td><td>${e.lastResponseTime ?? "—"}</td><td>${e.lastCheckedAt ? e.lastCheckedAt.toISOString() : "Never"}</td></tr>`
  )
  .join("\n")}
</tbody></table>
<p class="meta" style="margin-top:30px; text-align:center;">Degraded: ${degraded} | Generated by Pulse API Health Monitor</p>
</body></html>`;

    return new Response(html, {
      headers: {
        "Content-Type": "text/html",
        "Content-Disposition": `attachment; filename="pulse-dashboard-summary.html"`,
      },
    });
  } catch (err) {
    return error((err as Error).message, 500);
  }
}
