import { connectDB } from "@/lib/mongodb";
import Endpoint from "@/lib/models/endpoint";
import { error } from "@/lib/helpers/api-response";
import { requireAuth } from "@/lib/helpers/auth-guard";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export async function GET() {
  try {
    await requireAuth();
    await connectDB();

    const endpoints = await Endpoint.find().sort({ createdAt: -1 });

    const total = endpoints.length;
    const up = endpoints.filter((e) => e.lastStatus === "UP").length;
    const down = endpoints.filter((e) => e.lastStatus === "DOWN").length;
    const degraded = endpoints.filter((e) => e.lastStatus === "DEGRADED").length;
    const avgUptime =
      total > 0
        ? (endpoints.reduce((sum, e) => sum + e.uptimePercentage, 0) / total).toFixed(2)
        : "100.00";

    // Generate PDF
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Title
    doc.setFontSize(20);
    doc.setTextColor(30, 30, 30);
    doc.text("Pulse Dashboard Summary", 14, 22);

    // Divider line
    doc.setDrawColor(232, 135, 30);
    doc.setLineWidth(0.8);
    doc.line(14, 26, pageWidth - 14, 26);

    // Meta
    doc.setFontSize(10);
    doc.setTextColor(107, 114, 128);
    doc.text(`Generated: ${new Date().toISOString()}`, 14, 34);

    // Stats boxes
    const statsY = 42;
    const boxW = (pageWidth - 28 - 18) / 4;
    const stats = [
      { label: "Total Endpoints", value: String(total) },
      { label: "UP", value: String(up) },
      { label: "DOWN", value: String(down) },
      { label: "Avg Uptime", value: `${avgUptime}%` },
    ];

    stats.forEach((stat, i) => {
      const x = 14 + i * (boxW + 6);
      doc.setFillColor(249, 250, 251);
      doc.setDrawColor(229, 231, 235);
      doc.roundedRect(x, statsY, boxW, 28, 3, 3, "FD");
      doc.setFontSize(16);
      doc.setTextColor(30, 30, 30);
      doc.text(stat.value, x + boxW / 2, statsY + 13, { align: "center" });
      doc.setFontSize(8);
      doc.setTextColor(107, 114, 128);
      doc.text(stat.label, x + boxW / 2, statsY + 22, { align: "center" });
    });

    doc.setFontSize(10);
    doc.setTextColor(107, 114, 128);
    doc.text(`Degraded: ${degraded}`, 14, statsY + 36);

    // Endpoints table
    doc.setFontSize(14);
    doc.setTextColor(30, 30, 30);
    doc.text("All Endpoints", 14, statsY + 46);

    const tableData = endpoints.map((e) => [
      e.name,
      e.url.length > 40 ? e.url.substring(0, 40) + "..." : e.url,
      e.lastStatus || "PENDING",
      `${e.uptimePercentage.toFixed(2)}%`,
      e.lastResponseTime != null ? `${e.lastResponseTime}ms` : "—",
      e.lastCheckedAt ? new Date(e.lastCheckedAt).toLocaleString() : "Never",
    ]);

    autoTable(doc, {
      startY: statsY + 50,
      head: [["Name", "URL", "Status", "Uptime", "Response", "Last Check"]],
      body: tableData,
      styles: { fontSize: 7, cellPadding: 3 },
      headStyles: { fillColor: [232, 135, 30], textColor: 255, fontStyle: "bold" },
      columnStyles: {
        0: { cellWidth: 30 },
        1: { cellWidth: 50 },
        2: { cellWidth: 18 },
        3: { cellWidth: 20 },
        4: { cellWidth: 20 },
        5: { cellWidth: "auto" },
      },
      didParseCell(data) {
        if (data.section === "body" && data.column.index === 2) {
          const val = data.cell.raw as string;
          if (val === "UP") data.cell.styles.textColor = [34, 197, 94];
          else if (val === "DOWN") data.cell.styles.textColor = [239, 68, 68];
          else if (val === "DEGRADED") data.cell.styles.textColor = [234, 179, 8];
        }
      },
    });

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(156, 163, 175);
      doc.text(
        "Generated by Pulse API Health Monitor",
        pageWidth / 2,
        doc.internal.pageSize.getHeight() - 10,
        { align: "center" }
      );
    }

    const pdfBuffer = Buffer.from(doc.output("arraybuffer"));

    return new Response(pdfBuffer, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="pulse-dashboard-summary.pdf"`,
      },
    });
  } catch (err) {
    return error((err as Error).message, 500);
  }
}
