import { NextRequest } from "next/server";
import { connectDB } from "@/lib/mongodb";
import Endpoint from "@/lib/models/endpoint";
import CheckResult from "@/lib/models/check-result";
import { error } from "@/lib/helpers/api-response";
import { requireAuth } from "@/lib/helpers/auth-guard";

interface RouteParams {
  params: Promise<{ id: string }>;
}

export async function GET(req: NextRequest, { params }: RouteParams) {
  try {
    await requireAuth();
    await connectDB();

    const { id } = await params;
    const searchParams = req.nextUrl.searchParams;
    const from = searchParams.get("from");
    const to = searchParams.get("to");

    const endpoint = await Endpoint.findById(id);
    if (!endpoint) return error("Endpoint not found", 404);

    const query: Record<string, unknown> = { endpointId: id };
    if (from || to) {
      query.checkedAt = {};
      if (from) (query.checkedAt as Record<string, unknown>).$gte = new Date(from);
      if (to) (query.checkedAt as Record<string, unknown>).$lte = new Date(to);
    }

    const results = await CheckResult.find(query)
      .sort({ checkedAt: -1 })
      .limit(500);

    const upCount = results.filter((r) => r.status === "UP").length;
    const downCount = results.filter((r) => r.status === "DOWN").length;
    const degradedCount = results.filter((r) => r.status === "DEGRADED").length;
    const responseTimes = results
      .map((r) => r.responseTime)
      .filter((t): t is number => t !== null);
    const avgResponse = responseTimes.length
      ? Math.round(responseTimes.reduce((a, b) => a + b, 0) / responseTimes.length)
      : 0;

    // Generate HTML report (rendered as PDF-like downloadable HTML)
    const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Pulse Report: ${endpoint.name}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px 20px; color: #1a1a1a; }
  h1 { font-size: 24px; border-bottom: 2px solid #6366f1; padding-bottom: 8px; }
  h2 { font-size: 18px; color: #4b5563; margin-top: 30px; }
  .stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin: 20px 0; }
  .stat { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; }
  .stat-value { font-size: 28px; font-weight: 700; }
  .stat-label { font-size: 12px; color: #6b7280; }
  .up { color: #22c55e; } .down { color: #ef4444; } .degraded { color: #eab308; }
  table { width: 100%; border-collapse: collapse; margin-top: 16px; font-size: 13px; }
  th { background: #f3f4f6; text-align: left; padding: 8px 12px; border: 1px solid #e5e7eb; }
  td { padding: 8px 12px; border: 1px solid #e5e7eb; }
  .meta { color: #6b7280; font-size: 13px; margin: 8px 0; }
  @media print { body { padding: 0; } }
</style></head><body>
<h1>Pulse Report: ${endpoint.name}</h1>
<p class="meta">URL: ${endpoint.url} | Method: ${endpoint.method} | Generated: ${new Date().toISOString()}</p>
<div class="stats">
  <div class="stat"><div class="stat-value">${endpoint.uptimePercentage.toFixed(2)}%</div><div class="stat-label">Uptime</div></div>
  <div class="stat"><div class="stat-value up">${upCount}</div><div class="stat-label">UP Checks</div></div>
  <div class="stat"><div class="stat-value down">${downCount}</div><div class="stat-label">DOWN Checks</div></div>
  <div class="stat"><div class="stat-value">${avgResponse}ms</div><div class="stat-label">Avg Response</div></div>
</div>
<p class="meta">Total checks in report: ${results.length} | Degraded: ${degradedCount}</p>
<h2>Recent Check History</h2>
<table>
<thead><tr><th>Time</th><th>Status</th><th>Response (ms)</th><th>Error</th></tr></thead>
<tbody>
${results
  .slice(0, 100)
  .map(
    (r) =>
      `<tr><td>${r.checkedAt.toISOString()}</td><td class="${r.status.toLowerCase()}">${r.status}</td><td>${r.responseTime ?? "—"}</td><td>${r.error || "—"}</td></tr>`
  )
  .join("\n")}
</tbody></table>
<p class="meta" style="margin-top:30px; text-align:center;">Generated by Pulse API Health Monitor</p>
</body></html>`;

    return new Response(html, {
      headers: {
        "Content-Type": "text/html",
        "Content-Disposition": `attachment; filename="pulse-report-${endpoint.name.replace(/[^a-z0-9]/gi, "-")}.html"`,
      },
    });
  } catch (err) {
    return error((err as Error).message, 500);
  }
}
