import { NextRequest } from "next/server";
import { connectDB } from "@/lib/mongodb";
import Endpoint from "@/lib/models/endpoint";
import CheckResult from "@/lib/models/check-result";
import { error } from "@/lib/helpers/api-response";
import { requireAuth } from "@/lib/helpers/auth-guard";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

interface RouteParams {
  params: Promise<{ id: string }>;
}

export async function GET(req: NextRequest, { params }: RouteParams) {
  try {
    await requireAuth();
    await connectDB();

    const { id } = await params;
    const searchParams = req.nextUrl.searchParams;
    const from = searchParams.get("from");
    const to = searchParams.get("to");

    const endpoint = await Endpoint.findById(id);
    if (!endpoint) return error("Endpoint not found", 404);

    const query: Record<string, unknown> = { endpointId: id };
    if (from || to) {
      query.checkedAt = {};
      if (from) (query.checkedAt as Record<string, unknown>).$gte = new Date(from);
      if (to) (query.checkedAt as Record<string, unknown>).$lte = new Date(to);
    }

    const results = await CheckResult.find(query)
      .sort({ checkedAt: -1 })
      .limit(500);

    const upCount = results.filter((r) => r.status === "UP").length;
    const downCount = results.filter((r) => r.status === "DOWN").length;
    const degradedCount = results.filter((r) => r.status === "DEGRADED").length;
    const responseTimes = results
      .map((r) => r.responseTime)
      .filter((t): t is number => t !== null);
    const avgResponse = responseTimes.length
      ? Math.round(responseTimes.reduce((a, b) => a + b, 0) / responseTimes.length)
      : 0;

    // Generate PDF
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Title
    doc.setFontSize(20);
    doc.setTextColor(30, 30, 30);
    doc.text("Pulse Endpoint Report", 14, 22);

    // Divider line
    doc.setDrawColor(232, 135, 30);
    doc.setLineWidth(0.8);
    doc.line(14, 26, pageWidth - 14, 26);

    // Endpoint info
    doc.setFontSize(10);
    doc.setTextColor(107, 114, 128);
    doc.text(`Endpoint: ${endpoint.name}`, 14, 34);
    doc.text(`URL: ${endpoint.url}`, 14, 40);
    doc.text(`Method: ${endpoint.method} | Expected: ${endpoint.expectedStatusCode}`, 14, 46);
    doc.text(`Generated: ${new Date().toISOString()}`, 14, 52);

    // Stats boxes
    const statsY = 60;
    const boxW = (pageWidth - 28 - 18) / 4;
    const stats = [
      { label: "Uptime", value: `${endpoint.uptimePercentage.toFixed(2)}%` },
      { label: "UP Checks", value: String(upCount) },
      { label: "DOWN Checks", value: String(downCount) },
      { label: "Avg Response", value: `${avgResponse}ms` },
    ];

    stats.forEach((stat, i) => {
      const x = 14 + i * (boxW + 6);
      doc.setFillColor(249, 250, 251);
      doc.setDrawColor(229, 231, 235);
      doc.roundedRect(x, statsY, boxW, 28, 3, 3, "FD");
      doc.setFontSize(16);
      doc.setTextColor(30, 30, 30);
      doc.text(stat.value, x + boxW / 2, statsY + 13, { align: "center" });
      doc.setFontSize(8);
      doc.setTextColor(107, 114, 128);
      doc.text(stat.label, x + boxW / 2, statsY + 22, { align: "center" });
    });

    doc.setFontSize(10);
    doc.setTextColor(107, 114, 128);
    doc.text(`Total checks: ${results.length} | Degraded: ${degradedCount}`, 14, statsY + 36);

    // Check history table
    doc.setFontSize(14);
    doc.setTextColor(30, 30, 30);
    doc.text("Check History", 14, statsY + 46);

    const tableData = results.slice(0, 100).map((r) => [
      r.checkedAt ? new Date(r.checkedAt).toLocaleString() : "—",
      r.status,
      r.responseTime != null ? `${r.responseTime}ms` : "—",
      r.error || "—",
    ]);

    autoTable(doc, {
      startY: statsY + 50,
      head: [["Time", "Status", "Response", "Error"]],
      body: tableData,
      styles: { fontSize: 8, cellPadding: 3 },
      headStyles: { fillColor: [232, 135, 30], textColor: 255, fontStyle: "bold" },
      columnStyles: {
        0: { cellWidth: 45 },
        1: { cellWidth: 20 },
        2: { cellWidth: 25 },
        3: { cellWidth: "auto" },
      },
      didParseCell(data) {
        if (data.section === "body" && data.column.index === 1) {
          const val = data.cell.raw as string;
          if (val === "UP") data.cell.styles.textColor = [34, 197, 94];
          else if (val === "DOWN") data.cell.styles.textColor = [239, 68, 68];
          else if (val === "DEGRADED") data.cell.styles.textColor = [234, 179, 8];
        }
      },
    });

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(156, 163, 175);
      doc.text(
        "Generated by Pulse API Health Monitor",
        pageWidth / 2,
        doc.internal.pageSize.getHeight() - 10,
        { align: "center" }
      );
    }

    const pdfBuffer = Buffer.from(doc.output("arraybuffer"));

    return new Response(pdfBuffer, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="pulse-report-${endpoint.name.replace(/[^a-z0-9]/gi, "-")}.pdf"`,
      },
    });
  } catch (err) {
    return error((err as Error).message, 500);
  }
}
